server:
  port: 10000

server.servlet.context-path: /telecom

logging:
  level:
    ROOT: ERROR
    com.telecom.customer: ERROR

spring:
  flyway:
    enabled: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: false
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true